# This configuration is intended for dev purpose
name: dev-bookingdb
services:
  mysql:
    image: mysql:5.7.44
    container_name: dev-bookingdb-mysql
    restart: no
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=svc_testing_db
      - MYSQL_USER=svc_testing
      - MYSQL_PASSWORD=svc_testing
      - MYSQL_ROOT_PASSWORD=svc_root
      - TZ=UTC

  rabbitmq:
    container_name: dev-bookingdb-rabbitmq
    image: rabbitmq:management-alpine
    restart: no
    environment:
      - RABBITMQ_DEFAULT_USER=svc_testing
      - RABBITMQ_DEFAULT_PASS=svc_testing
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"

  prometheus:
    container_name: dev-bookingdb-prometheus
    image: prom/prometheus:v3.1.0
    volumes:
      - ./src/main/docker/prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    # On MacOS, remove next line and replace localhost by host.docker.internal in src/main/docker/prometheus/prometheus.yml and
    # docker/grafana/provisioning/datasources/datasource.yml
    network_mode: "host" # to test locally running service
  grafana:
    container_name: dev-bookingdb-grafana
    image: grafana/grafana:11.4.0
    volumes:
      - ./src/main/docker/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=changeme
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    # On MacOS, remove next line and replace localhost by host.docker.internal in src/main/docker/prometheus/prometheus.yml and
    # docker/grafana/provisioning/datasources/datasource.yml
    network_mode: "host" # to test locally running service
